version: '{build}'
skip_tags: true
image: Visual Studio 2019
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/ZBlazor.QuickInput.*.nupkg
deploy:
- provider: NuGet
  on:
    branch: /^(master|dev)$/
